### ISSUE TITLE
Bug: `<after>` section interrupted at failure

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2-functional-testing-framework#661] opened 2020-03-28 18:58 UTC
Tests' `<after>` section should rollback the state of the application to the previous state even if test failed and not all the actions were performed. That's important part of Test isolation.

### Preconditions
1. Even if one of the steps fails, the rest of `<after>` section is being run

### Steps to reproduce
1. Create test that has 3 `<createData` in `<before>` section
2. Add some failing action like some `<amOnPage>` to `<after>` section
3. Add 3 `<deleteData` in `<after>` section after (2) that refer to `<createData`

### Expected result
1. `<amOnPage` should fail, but `<deleteData>` should still be executed

### Actual result
1. `<amOnPage` fails but no more steps are run.

**Comment by jilu1** [comment] 2020-04-01 16:35
@lbajsarowicz Thanks for reporting the issue and providing a PR! Please fix static test errors so we can review your PR.

**Comment by lbajsarowicz** [comment] 2020-04-18 18:20
We need to review that after upgrade of Codeception

**Comment by jilu1** [comment] 2020-07-27 22:18
@lbajsarowicz I could not reproduce the issue using MFTF 3.0.0 (with Codeception 4.1.4). I will close this since it's been very long. Free free to reopen if this is still an issue.

**Closed by jilu1** 2020-07-27 22:18 UTC
Labels: accept, acknowledged, bugfix, hasPR
